version: "3"
services: 
    api:
        build: .
        depends_on:
            - postgres
        ports:
            - 4000:8000
        
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

        # env_file:
        #    - ./.env
        environment: 
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=45Onelove!
            - DATABASE_NAME=fastapi 
            - DATABASE_USERNAME=postgres 
            - SECRET_KEY=4a92f6d42d0f8194a723f89f573ac12c9b0a621c52122a07a2328510b3f8a34a
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30

    postgres:
            image: postgres
            environment:
                    - POSTGRES_PASSWORD=password123
                    - POSTGRES_DB=fastapi

            volumes:
                - postgres-db:/var/lib/postgresql/data

volumes: 
    postgres-db: 

